# Numpy Practice
source: https://pynative.com/python-numpy-exercise/

#### Create a 4X2 integer array and Prints its attributes

Note: element must be a type of unsigned int16. And print the following Attributes: –

* The shape of an array.
* Array dimensions.
* The Length of each element of the array in bytes.

In [7]:
import numpy as np
firstArray = np.empty([4,2], dtype = np.uint16)

print("The Array is:")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)



The Array is:
[[    0     0]
 [    0 16384]
 [43626 32839]
 [ 2045 36864]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


#### Create a 5X2 integer array 
from a range between 100 to 200 such that the difference between each element is 10

In [9]:
print("Creating 5X2 array using numpy.arange")
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


#### Following is the provided numPy array. return array of items in the third column from all rows

```
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
```

In [11]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)
print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[:,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]
